### ISSUE TITLE
Votes impossibles

### ISSUE THREAD

**Issue by couillardcharles** [okiwi/LightningTalk#2]
Hello,

il y a un problème sur la session d'Olivier Azeau, impossible de voter :

Failed to load resource: the server responded with a status of 400 (Bad Request) http://lightningtalk.herokuapp.com/sessions/Que%20faire%20si%20la%20v%C3%A9locit%C3%A9%20ne%20fonctionne%20pas%20?/votants
POST http://lightningtalk.herokuapp.com/sessions/Que%20faire%20si%20la%20v%C3%A9locit%C3%A9%20ne%20fonctionne%20pas%20?/votants 400 (Bad Request)

**Comment by couillardcharles** [comment]
Je vote pour le point d'interrogation à la fin de son sujet :)

"Que faire si la vélocité ne fonctionne pas ?"

**Comment by guillaumevincent** [comment]
oui je pense aussi
Jérôme a la main dessus

Je ne peux rien faire

On Wed, Oct 3, 2012 at 9:18 AM, Charles Couillard
notifications@github.comwrote:

> Je vote pour le point d'interrogation à la fin de son sujet :)
> 
> "Que faire si la vélocité ne fonctionne pas ?"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/okiwi/LightningTalk/issues/2#issuecomment-9097700.

## 

_Guillaume VINCENT_
_06 66 30 70 15_
Blog http://vincentguillaume.fr/
Twitter http://twitter.com/rolalagile
Profil Google+ https://plus.google.com/u/0/101137288862468153673/

**Comment by roux-jerome** [comment]
c'est bien le point d'interrogation qui pose problème. J'ai pousser sous github la correction. Quelqu'un peut le déployer sur heroku ? sinon ce sera ce soir !
